apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::951151046739:user/jenkins-pipeline-user
      username: jenkins-pipeline-user
      groups:
        - system:masters
    - userarn: arn:aws:iam::951151046739:user/jayadeep
      username: jayadeep
      groups:
        - system:masters
