spring.application.name=aws_spring_application
# Enable the H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL statements in the console (helpful for debugging)
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb